-- 20260908170000: 活动待办（v1.7.1 Activity Tasks）
-- 每个活动拥有自己的待办任务；任务是活动的子记录（硬删除），不进全局 task center
-- 多态关联 related_type: none/customer/recruit/speaker/activity（不建外键，与 activity_participants 同款模式）

CREATE TABLE IF NOT EXISTS activity_tasks (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id   bigint      NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
    task_title    text        NOT NULL,
    task_type     text        NOT NULL DEFAULT 'other',      -- preparation/invitation/speaker/onsite/followup/review/other
    status        text        NOT NULL DEFAULT 'pending',    -- pending/in_progress/completed/skipped
    priority      text        NOT NULL DEFAULT 'medium',     -- high/medium/low
    due_date      date,
    completed_at  timestamptz,
    related_type  text        NOT NULL DEFAULT 'none',       -- none/customer/recruit/speaker/activity
    related_id    bigint,
    note          text,
    source        text        NOT NULL DEFAULT 'manual',     -- manual/ai/template
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT activity_tasks_task_type_check
      CHECK (task_type IN ('preparation','invitation','speaker','onsite','followup','review','other')),
    CONSTRAINT activity_tasks_status_check
      CHECK (status IN ('pending','in_progress','completed','skipped')),
    CONSTRAINT activity_tasks_priority_check
      CHECK (priority IN ('high','medium','low')),
    CONSTRAINT activity_tasks_related_type_check
      CHECK (related_type IN ('none','customer','recruit','speaker','activity')),
    CONSTRAINT activity_tasks_source_check
      CHECK (source IN ('manual','ai','template'))
);

CREATE INDEX IF NOT EXISTS idx_activity_tasks_activity
    ON activity_tasks (activity_id);
CREATE INDEX IF NOT EXISTS idx_activity_tasks_status_due
    ON activity_tasks (status, due_date);
CREATE INDEX IF NOT EXISTS idx_activity_tasks_related
    ON activity_tasks (related_type, related_id);

COMMENT ON TABLE activity_tasks IS '活动待办任务（活动子记录，硬删除；不进全局 task center）';
COMMENT ON COLUMN activity_tasks.task_type IS 'preparation(筹备)/invitation(邀约)/speaker(嘉宾)/onsite(现场)/followup(跟进)/review(复盘)/other(其他)';
COMMENT ON COLUMN activity_tasks.status IS 'pending(待办)/in_progress(进行中)/completed(已完成)/skipped(已跳过)';
COMMENT ON COLUMN activity_tasks.priority IS 'high(高)/medium(中)/low(低)';
COMMENT ON COLUMN activity_tasks.related_type IS 'none/customer/recruit/speaker/activity 多态关联，related_id 对应人员或活动 id';
COMMENT ON COLUMN activity_tasks.source IS 'manual(手动)/ai(AI建议,本版本无入口)/template(模板,本版本无入口)';

-- RLS：fn_only（与 activities/activity_participants 同款）
ALTER TABLE public.activity_tasks ENABLE ROW LEVEL SECURITY;
CREATE POLICY activity_tasks_fn_only ON public.activity_tasks
  FOR ALL TO anon
  USING ((((current_setting('request.jwt.claims'::text, true))::json ->> 'sub'::text) IS NULL) AND (((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'anon'::text))
  WITH CHECK ((((current_setting('request.jwt.claims'::text, true))::json ->> 'sub'::text) IS NULL) AND (((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'anon'::text));

-- 授权（对齐 activities）
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.activity_tasks TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, TRIGGER, TRUNCATE ON TABLE public.activity_tasks TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, TRIGGER, TRUNCATE ON TABLE public.activity_tasks TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, TRIGGER, TRUNCATE ON TABLE public.activity_tasks TO cloudbase_postgres_pgdb_pn3idppt;
GRANT USAGE, SELECT ON SEQUENCE activity_tasks_id_seq TO anon, authenticated;
