-- 20260909100000: 活动主题资源池（v1.7.4 Activity Topic Pool）
-- 可复用的活动主题资源；与 activities.topic_ids(jsonb) 弱关联（存主题 id 数组），不建关联表
-- 删除采用软删除（deleted_at）；使用统计直接写本表（use_count/last_used_date），不建统计表
--
-- 本文件为该版本单一事实来源，全部语句幂等，可在新环境完整重放。

CREATE TABLE IF NOT EXISTS activity_topics (
    id                 bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_name         text        NOT NULL,
    category           text,
    description        text,
    target_audience    text,
    keywords           jsonb       NOT NULL DEFAULT '[]'::jsonb,
    status             text        NOT NULL DEFAULT 'active',  -- active/inactive
    last_used_date     date,
    use_count          integer     NOT NULL DEFAULT 0,
    ai_summary         text,
    notes              text,
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now(),
    deleted_at         timestamptz,
    CONSTRAINT activity_topics_status_check
      CHECK (status IN ('active','inactive')),
    CONSTRAINT activity_topics_use_count_check
      CHECK (use_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_activity_topics_name
    ON activity_topics (topic_name);
CREATE INDEX IF NOT EXISTS idx_activity_topics_category
    ON activity_topics (category);
CREATE INDEX IF NOT EXISTS idx_activity_topics_status
    ON activity_topics (status);

COMMENT ON TABLE activity_topics IS '活动主题资源池（可复用主题档案，软删除；与 activities.topic_ids 弱关联，不建关联表）';
COMMENT ON COLUMN activity_topics.keywords IS '关键词数组（jsonb 字符串数组）';
COMMENT ON COLUMN activity_topics.use_count IS '被活动采用次数（用户确认主题用于活动时 +1，移除不回退）';
COMMENT ON COLUMN activity_topics.last_used_date IS '最近一次被采用的活动日期（无活动日期则取当天）';
COMMENT ON COLUMN activity_topics.status IS 'active(可用)/inactive(停用)';

-- RLS：fn_only（与 activity_speakers/activity_tasks 同款）；DROP+CREATE 保证重放幂等
ALTER TABLE public.activity_topics ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS activity_topics_fn_only ON public.activity_topics;
CREATE POLICY activity_topics_fn_only ON public.activity_topics
  FOR ALL TO anon
  USING ((((current_setting('request.jwt.claims'::text, true))::json ->> 'sub'::text) IS NULL) AND (((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'anon'::text))
  WITH CHECK ((((current_setting('request.jwt.claims'::text, true))::json ->> 'sub'::text) IS NULL) AND (((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'anon'::text));

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.activity_topics TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, TRIGGER, TRUNCATE ON TABLE public.activity_topics TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, TRIGGER, TRUNCATE ON TABLE public.activity_topics TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, TRIGGER, TRUNCATE ON TABLE public.activity_topics TO cloudbase_postgres_pgdb_pn3idppt;
GRANT USAGE, SELECT ON SEQUENCE activity_topics_id_seq TO anon, authenticated;
