-- 20260909000000: 活动嘉宾资源池（v1.7.3 Activity Speaker Pool）
-- 可复用的嘉宾资源池；不与客户/候选人建强 FK（弱关联，仅存 id）
-- 删除采用软删除（deleted_at），与资源池数据复用惯例一致

CREATE TABLE IF NOT EXISTS activity_speakers (
    id                   bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 text        NOT NULL,
    phone                text,
    wechat               text,
    organization         text,
    position             text,
    relationship_stage   text        NOT NULL DEFAULT 'new',   -- new/contacted/cooperated/stable/deep/inactive
    expertise            text,
    topic_summary        text,
    source               text,
    last_contact_date    date,
    next_contact_date    date,
    last_contact_note    text,
    cooperation_count    integer     NOT NULL DEFAULT 0,
    preferred_format     text,
    status               text        NOT NULL DEFAULT 'active', -- active/inactive
    customer_id          bigint,
    recruit_candidate_id bigint,
    notes                text,
    created_at           timestamptz NOT NULL DEFAULT now(),
    updated_at           timestamptz NOT NULL DEFAULT now(),
    deleted_at           timestamptz,
    CONSTRAINT activity_speakers_relationship_stage_check
      CHECK (relationship_stage IN ('new','contacted','cooperated','stable','deep','inactive')),
    CONSTRAINT activity_speakers_status_check
      CHECK (status IN ('active','inactive')),
    CONSTRAINT activity_speakers_cooperation_count_check
      CHECK (cooperation_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_activity_speakers_name
    ON activity_speakers (name);
CREATE INDEX IF NOT EXISTS idx_activity_speakers_org
    ON activity_speakers (organization);
CREATE INDEX IF NOT EXISTS idx_activity_speakers_status
    ON activity_speakers (status);

COMMENT ON TABLE activity_speakers IS '活动嘉宾资源池（可复用嘉宾档案，软删除；不与客户/候选人建强外键）';
COMMENT ON COLUMN activity_speakers.relationship_stage IS 'new(新)/contacted(已联系)/cooperated(已合作)/stable(稳定)/deep(深度)/inactive(不活跃)';
COMMENT ON COLUMN activity_speakers.cooperation_count IS '合作次数（本版本仅手动维护，不自动累加）';
COMMENT ON COLUMN activity_speakers.preferred_format IS '偏好形式（如线上/线下/主题分享等，自由文本）';
COMMENT ON COLUMN activity_speakers.status IS 'active(可用)/inactive(停用)';

-- person_id 扩为 bigint：person_type='speaker' 时存 activity_speakers.id（bigint），与 customers.Id bigint 对齐
ALTER TABLE public.activity_participants ALTER COLUMN person_id TYPE bigint;

-- RLS：fn_only（与 activity_tasks 同款）
ALTER TABLE public.activity_speakers ENABLE ROW LEVEL SECURITY;
CREATE POLICY activity_speakers_fn_only ON public.activity_speakers
  FOR ALL TO anon
  USING ((((current_setting('request.jwt.claims'::text, true))::json ->> 'sub'::text) IS NULL) AND (((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'anon'::text))
  WITH CHECK ((((current_setting('request.jwt.claims'::text, true))::json ->> 'sub'::text) IS NULL) AND (((current_setting('request.jwt.claims'::text, true))::json ->> 'role'::text) = 'anon'::text));

-- 授权（对齐 activity_tasks）
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.activity_speakers TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, TRIGGER, TRUNCATE ON TABLE public.activity_speakers TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, TRIGGER, TRUNCATE ON TABLE public.activity_speakers TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, TRIGGER, TRUNCATE ON TABLE public.activity_speakers TO cloudbase_postgres_pgdb_pn3idppt;
GRANT USAGE, SELECT ON SEQUENCE activity_speakers_id_seq TO anon, authenticated;
